# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tony Wang
email: tonywang.data@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog related to programming and reading
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonywang.io" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-39691010-9

github_username:  tonywangcn
repository: tonywangcn/blog
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

gems:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata

permalink: /:year/:month/:title.html

pagination:
  enabled: true
  debug: true
  # collection: 'post'
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

port: 4000
host: 0.0.0.0

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - dockerfile
  - docker-compose.yml
  - dev.env
  - Makefile
  - README.md
  # - index.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
