version: '3.5'
services:
  jekyll:
    container_name: jekyll-cayman
    image: jekyll-cayman
    # image: jekyll/builder:3.8
    build: ./
    restart: always
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "4000:4000"
    # command: ["tail", "-f", "/dev/null"]
    command: ["bundle", "exec", "jekyll", "serve"]
    env_file: dev.env
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"